### ISSUE TITLE
Meet Rooms giving a 503.

### ISSUE THREAD

**Issue by tylerjfields** [emerald-co/emeraldchat.com#10] opened 2017-03-22 04:39 UTC
"Failed to load resource: the server responded with a status of 503 ()" while attempting to access the group rooms listing.

**Comment by tylerjfields** [comment] 2017-03-22 04:51
Failed to load resource: the server responded with a status of 503 ()
https://www.emeraldchat.com/room?id=547065 Failed to load resource: the server responded with a status of 503 ()
application-99cae558acbe9b805c52e97615244da2e9df019a408bef358a0b0f49b1fcee5d.js:5 behavior: navbar-messages data: [object Object]
application-99cae558acbe9b805c52e97615244da2e9df019a408bef358a0b0f49b1fcee5d.js:5 behavior: messages-load data: [object Object]
https://www.emeraldchat.com/update_notifications Failed to load resource: the server responded with a status of 503 ()
https://www.emeraldchat.com/room?id=547065 Failed to load resource: the server responded with a status of 503 ()
2https://googleads.g.doubleclick.net/pagead/id Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
https://www.emeraldchat.com/room?id=547065 Failed to load resource: the server responded with a status of 503 ()
application-99cae558acbe9b805c52e97615244da2e9df019a408bef358a0b0f49b1fcee5d.js:5 behavior: navbar-messages data: [object Object]
application-99cae558acbe9b805c52e97615244da2e9df019a408bef358a0b0f49b1fcee5d.js:5 behavior: messages-load data: [object Object]
3application-99cae558acbe9b805c52e97615244da2e9df019a408bef358a0b0f49b1fcee5d.js:5 behavior: undefined data: [object Object]
VM486:142 [Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object, Object]
application-99cae55….js:4 ### initialized room with id 547065 ###
application-99cae55….js:5 behavior: room_speaker data: [object Object]
room Failed to load resource: the server responded with a status of 503 ()
application-99cae55….js:5 behavior: room_speaker data: [object Object]
room Failed to load resource: the server responded with a status of 503 ()

**Comment by emerald-co** [comment] 2017-03-23 10:33
Hey there,

could you tell us the steps to recreate this?

**Comment by emerald-co** [comment] 2017-03-23 10:36
Room's aren't supposed to be accessed via URL therefore will not work as such. I'm guessing this is what you were trying to do. this is intended behavior and thus not an issue. Going to close it now. Thanks for rasing!

**Closed as completed by emerald-co** 2017-03-23 10:36 UTC
